### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Firescar96**
add datland-swarm-defaults

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
The `datland-swarm-defaults` package doesn't seem to exist on npm. There is a `dat-swarm-defaults` though?

**Comment by MTonomy-Nchinda-Nchinda** [comment]
You are correct, in the past couple months the former package has become deprecated https://www.npmjs.com/package/datland-swarm-defaults

**Comment by Firescar96** [comment]
You are correct, in the past couple months the former package has become deprecated https://www.npmjs.com/package/datland-swarm-defaults

**Comment by pvh** [comment]
Hi! Just doing some cleanup since I'm working on this again. This is fixed in master :)

**Pull request closed without merging**
