### PR TITLE
New sample for working with 2 Repos

### PR DESCRIPTION
**Pull request by johnptoohey**

### CODE REVIEW

**Comment by pvh** [comment]
Hey John, this is great! I got pulled into the Christmas vortex and hadn't had time to review until today. My first cursory look makes me a little sad, not for the code you're submitting, but for the state of hypermerge that you had to bash in all those type definitions. I'll take a closer look as soon as I can but my initial impression is that it would be nice to cut down a lot of that boilerplate in the example by making it available more generally.

**Comment by johnptoohey** [comment]
I agree, but not sure the bet place to pull them in from. Spent some time over the holidays, trying to get Hypermerge running with Deno, but failed with type problems. Let me know what next steps are.

**Comment by pvh** [comment]
I'm not sure I'll be able to get to it before Monday but I plan to go through the patch more thoroughly, and will either leave comments or just fix things and hope to land it that day.

**Comment by pvh** [comment]
Hey @johnptoohey -- dug into this and I see you've added a bunch of types that don't seem to be necessary for the example but are pretty thoroughly worked out. Can you explain that a bit?

**Comment by pvh** [comment]
Oh, now I see you've just copied the types directory into the example. I'll clean that up and land the patch. Thanks for the contribution!

**Pull request closed without merging**
